"""Initial migration - create all tables

Revision ID: 8b1eea533361
Revises:
Create Date: 2026-02-10 16:44:55.949413

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8b1eea533361"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_timeseries",
        sa.Column("user_id", sa.UUID(), nullable=False, comment="사용자 ID"),
        sa.Column("timestamp", sa.TIMESTAMP(), nullable=False, comment="타임스탬프"),
        sa.Column("mcdi_score", sa.Float(), nullable=False, comment="MCDI 종합 점수"),
        sa.Column("lr_score", sa.Float(), nullable=True, comment="어휘 풍부도"),
        sa.Column("sd_score", sa.Float(), nullable=True, comment="의미적 표류"),
        sa.Column("nc_score", sa.Float(), nullable=True, comment="서사 일관성"),
        sa.Column("to_score", sa.Float(), nullable=True, comment="시간적 지남력"),
        sa.Column("er_score", sa.Float(), nullable=True, comment="일화 기억"),
        sa.Column("rt_score", sa.Float(), nullable=True, comment="반응 시간"),
        sa.Column("risk_level", sa.String(length=20), nullable=True, comment="위험도"),
        sa.PrimaryKeyConstraint("user_id", "timestamp"),
    )
    op.create_table(
        "guardians",
        sa.Column("id", sa.UUID(), nullable=False, comment="보호자 고유 ID"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="보호자 이름"),
        sa.Column("phone", sa.String(length=20), nullable=True, comment="전화번호"),
        sa.Column("email", sa.String(length=100), nullable=True, comment="이메일"),
        sa.Column("kakao_id", sa.String(length=100), nullable=True, comment="카카오톡 ID"),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성 시각",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_guardians_email"), "guardians", ["email"], unique=False)
    op.create_index(op.f("ix_guardians_phone"), "guardians", ["phone"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False, comment="사용자 고유 ID"),
        sa.Column("kakao_id", sa.String(length=100), nullable=False, comment="카카오톡 ID"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="사용자 이름"),
        sa.Column("birth_date", sa.Date(), nullable=True, comment="생년월일"),
        sa.Column("gender", sa.String(length=10), nullable=True, comment="성별"),
        sa.Column("phone", sa.String(length=20), nullable=True, comment="전화번호"),
        sa.Column("email", sa.String(length=100), nullable=True, comment="이메일"),
        sa.Column("baseline_mcdi", sa.Float(), nullable=True, comment="개인 baseline MCDI 점수"),
        sa.Column(
            "baseline_established_at", sa.TIMESTAMP(), nullable=True, comment="baseline 설정 시각"
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성 시각",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="수정 시각",
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True, comment="삭제 시각 (Soft Delete)"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_kakao_id"), "users", ["kakao_id"], unique=True)
    op.create_table(
        "conversations",
        sa.Column(
            "id", sa.BigInteger(), autoincrement=True, nullable=False, comment="대화 고유 ID"
        ),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="사용자 ID"),
        sa.Column("message", sa.Text(), nullable=False, comment="사용자 메시지"),
        sa.Column("response", sa.Text(), nullable=True, comment="AI 응답"),
        sa.Column("message_type", sa.String(length=20), nullable=False, comment="메시지 타입"),
        sa.Column("image_url", sa.Text(), nullable=True, comment="이미지 URL"),
        sa.Column("category", sa.String(length=50), nullable=True, comment="대화 카테고리"),
        sa.Column(
            "response_latency_ms", sa.Integer(), nullable=True, comment="응답 지연 시간 (ms)"
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성 시각",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversations_category"), "conversations", ["category"], unique=False)
    op.create_index(
        op.f("ix_conversations_created_at"), "conversations", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.create_table(
        "garden_status",
        sa.Column("user_id", sa.UUID(), nullable=False, comment="사용자 ID"),
        sa.Column("flower_count", sa.Integer(), nullable=False, comment="꽃 개수"),
        sa.Column("butterfly_count", sa.Integer(), nullable=False, comment="나비 개수"),
        sa.Column("consecutive_days", sa.Integer(), nullable=False, comment="연속 참여 일수"),
        sa.Column("total_conversations", sa.Integer(), nullable=False, comment="총 대화 수"),
        sa.Column(
            "last_interaction_at", sa.TIMESTAMP(), nullable=True, comment="마지막 상호작용 시각"
        ),
        sa.Column("season_badge", sa.String(length=50), nullable=True, comment="계절 뱃지"),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="수정 시각",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "notifications",
        sa.Column(
            "id", sa.BigInteger(), autoincrement=True, nullable=False, comment="알림 고유 ID"
        ),
        sa.Column("guardian_id", sa.UUID(), nullable=False, comment="보호자 ID"),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="사용자 ID"),
        sa.Column(
            "type", sa.String(length=50), nullable=False, comment="알림 타입 (concern/urgent/info)"
        ),
        sa.Column("title", sa.String(length=200), nullable=False, comment="알림 제목"),
        sa.Column("content", sa.Text(), nullable=False, comment="알림 내용"),
        sa.Column("risk_level", sa.String(length=20), nullable=True, comment="위험도"),
        sa.Column(
            "analysis_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="분석 결과 스냅샷",
        ),
        sa.Column(
            "sent_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="발송 시각",
        ),
        sa.Column("read_at", sa.TIMESTAMP(), nullable=True, comment="읽음 시각"),
        sa.ForeignKeyConstraint(["guardian_id"], ["guardians.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_guardian_id"), "notifications", ["guardian_id"], unique=False
    )
    op.create_index(op.f("ix_notifications_sent_at"), "notifications", ["sent_at"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "user_guardians",
        sa.Column("user_id", sa.UUID(), nullable=False, comment="사용자 ID"),
        sa.Column("guardian_id", sa.UUID(), nullable=False, comment="보호자 ID"),
        sa.Column(
            "relation",
            sa.String(length=50),
            nullable=True,
            comment="관계 (daughter/son/spouse/caregiver)",
        ),
        sa.Column("notification_enabled", sa.Boolean(), nullable=False, comment="알림 활성화 여부"),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성 시각",
        ),
        sa.ForeignKeyConstraint(["guardian_id"], ["guardians.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "guardian_id"),
    )
    op.create_table(
        "analysis_results",
        sa.Column(
            "id", sa.BigInteger(), autoincrement=True, nullable=False, comment="분석 결과 고유 ID"
        ),
        sa.Column("conversation_id", sa.BigInteger(), nullable=False, comment="대화 ID"),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="사용자 ID"),
        sa.Column("mcdi_score", sa.Float(), nullable=False, comment="MCDI 종합 점수"),
        sa.Column(
            "risk_level",
            sa.String(length=20),
            nullable=False,
            comment="위험도 (GREEN/YELLOW/ORANGE/RED)",
        ),
        sa.Column("lr_score", sa.Float(), nullable=True, comment="어휘 풍부도 (Lexical Richness)"),
        sa.Column(
            "lr_detail",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="어휘 풍부도 상세 분석",
        ),
        sa.Column("sd_score", sa.Float(), nullable=True, comment="의미적 표류 (Semantic Drift)"),
        sa.Column(
            "sd_detail",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="의미적 표류 상세 분석",
        ),
        sa.Column(
            "nc_score", sa.Float(), nullable=True, comment="서사 일관성 (Narrative Coherence)"
        ),
        sa.Column(
            "nc_detail",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="서사 일관성 상세 분석",
        ),
        sa.Column(
            "to_score", sa.Float(), nullable=True, comment="시간적 지남력 (Temporal Orientation)"
        ),
        sa.Column(
            "to_detail",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="시간적 지남력 상세 분석",
        ),
        sa.Column("er_score", sa.Float(), nullable=True, comment="일화 기억 (Episodic Recall)"),
        sa.Column(
            "er_detail",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="일화 기억 상세 분석",
        ),
        sa.Column("rt_score", sa.Float(), nullable=True, comment="반응 시간 (Response Time)"),
        sa.Column(
            "rt_detail",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="반응 시간 상세 분석",
        ),
        sa.Column(
            "contradictions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="모순 탐지 결과",
        ),
        sa.Column(
            "confounds_detected",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="교란 변수 탐지",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성 시각",
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_results_created_at"), "analysis_results", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_results_mcdi_score"), "analysis_results", ["mcdi_score"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_results_risk_level"), "analysis_results", ["risk_level"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_results_user_id"), "analysis_results", ["user_id"], unique=False
    )
    op.create_table(
        "memory_events",
        sa.Column(
            "id", sa.BigInteger(), autoincrement=True, nullable=False, comment="이벤트 고유 ID"
        ),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="사용자 ID"),
        sa.Column("conversation_id", sa.BigInteger(), nullable=True, comment="대화 ID"),
        sa.Column("event_type", sa.String(length=50), nullable=False, comment="이벤트 타입"),
        sa.Column("entity", sa.String(length=100), nullable=True, comment="엔티티"),
        sa.Column("old_value", sa.Text(), nullable=True, comment="이전 값"),
        sa.Column("new_value", sa.Text(), nullable=True, comment="새로운 값"),
        sa.Column(
            "severity", sa.String(length=20), nullable=True, comment="심각도 (high/medium/low)"
        ),
        sa.Column("confidence", sa.Float(), nullable=True, comment="신뢰도"),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성 시각",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_events_event_type"), "memory_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_memory_events_severity"), "memory_events", ["severity"], unique=False)
    op.create_index(op.f("ix_memory_events_user_id"), "memory_events", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_memory_events_user_id"), table_name="memory_events")
    op.drop_index(op.f("ix_memory_events_severity"), table_name="memory_events")
    op.drop_index(op.f("ix_memory_events_event_type"), table_name="memory_events")
    op.drop_table("memory_events")
    op.drop_index(op.f("ix_analysis_results_user_id"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_risk_level"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_mcdi_score"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_created_at"), table_name="analysis_results")
    op.drop_table("analysis_results")
    op.drop_table("user_guardians")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_sent_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_guardian_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("garden_status")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_created_at"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_category"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_users_kakao_id"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_guardians_phone"), table_name="guardians")
    op.drop_index(op.f("ix_guardians_email"), table_name="guardians")
    op.drop_table("guardians")
    op.drop_table("analysis_timeseries")
    # ### end Alembic commands ###
