"""add_fcm_tokens_table

Revision ID: fd473cec7546
Revises: 6c8bb27a7932
Create Date: 2026-02-23 14:35:42.569793

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fd473cec7546"
down_revision: Union[str, Sequence[str], None] = "6c8bb27a7932"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fcm_tokens",
        sa.Column(
            "id", sa.BigInteger(), autoincrement=True, nullable=False, comment="토큰 고유 ID"
        ),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="사용자 ID"),
        sa.Column("token", sa.String(length=255), nullable=False, comment="FCM 등록 토큰"),
        sa.Column(
            "device_type",
            sa.String(length=20),
            nullable=True,
            comment="기기 타입 (android/ios/web)",
        ),
        sa.Column("device_id", sa.String(length=100), nullable=True, comment="기기 고유 ID"),
        sa.Column("device_name", sa.String(length=100), nullable=True, comment="기기 이름"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="활성 상태"),
        sa.Column("last_used_at", sa.TIMESTAMP(), nullable=True, comment="마지막 사용 시각"),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성 시각",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="수정 시각",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fcm_tokens_is_active"), "fcm_tokens", ["is_active"], unique=False)
    op.create_index(op.f("ix_fcm_tokens_token"), "fcm_tokens", ["token"], unique=True)
    op.create_index(op.f("ix_fcm_tokens_user_id"), "fcm_tokens", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fcm_tokens_user_id"), table_name="fcm_tokens")
    op.drop_index(op.f("ix_fcm_tokens_token"), table_name="fcm_tokens")
    op.drop_index(op.f("ix_fcm_tokens_is_active"), table_name="fcm_tokens")
    op.drop_table("fcm_tokens")
    # ### end Alembic commands ###
