"""Add kakao oauth tokens to users table

Revision ID: 6da46d0d1818
Revises: fd473cec7546
Create Date: 2026-02-24 11:01:07.032764

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6da46d0d1818"
down_revision: Union[str, Sequence[str], None] = "fd473cec7546"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kakao_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('kakao_refresh_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('kakao_token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('kakao_refresh_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kakao_refresh_token_expires_at')
    op.drop_column('users', 'kakao_token_expires_at')
    op.drop_column('users', 'kakao_refresh_token')
    op.drop_column('users', 'kakao_access_token')
    # ### end Alembic commands ###
